name: repo events
on:
  push:
  pull_request:
    types: [opened, assigned]
  issues:
    types: [opened]

jobs:
  checkout-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
